name: cd

on:
  push:
    branches: [ main ]
  release:
      types: [published, created, edited]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: |
          ghcr.io/spruceid/didkit-http
        tags: |
          type=ref,event=branch
          type=sha,prefix={{date 'YYYYMMDDHHmmss'}}
          type=raw,value=latest,enable={{is_default_branch}}
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v6
      with:
        # https://github.com/docker/build-push-action/tree/090ca155fc9b214cbcac536c450455a0e96f52c6?tab=readme-ov-file#git-context
        # to make sure .dockerignore is used
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
